Here is a production-ready prompt you can drop into any AI agent:

---

**SYSTEM / TASK PROMPT**

---

## Project: HTML Invoice Report → Excel Converter (Web App)

### Overview

Build a **single-page web application** (pure HTML + CSS + JavaScript, no backend, no frameworks required) that allows a user to upload an HTML invoice report file and automatically converts it into a clean, well-formatted **Excel (.xlsx) file** for download.

The HTML report files this tool will process are always generated by a legacy VFP/MSHTML print engine and have a **fixed, known structure** described in detail below. The app must parse that structure precisely and export structured data.

---

### Input File Structure (Critical — Read Carefully)

The HTML file has these exact characteristics:

1. **All content is rendered using absolutely positioned `<div>` tags** — there are NO `<table>` elements for data. Every row of data is a `<div>` with an inline `style` containing `top: Npx` (vertical position) and `left: 5px`.

2. **CSS class:** All data divs have `class="font1"`. Non-printable border divs have `class="basenotprint"` — **ignore those entirely**.

3. **Pages:** The report can span multiple pages. Each page is wrapped in `<div class="page" style="width:793px; height:1122px; ...">`. Each page is **1122px tall**. To get the true vertical order of a line, calculate its **absolute top position** as:
   ```
   absolute_top = (page_index × 1122) + div's_top_value
   ```
   Page index starts at 0.

4. **Character encoding:** The file uses `windows-1252` encoding. The non-breaking hyphen character `&#8209;` (Unicode `\u2011`) is used both as a **dash placeholder** (meaning zero/nil in Free Qty column) and as a **separator line filler**. Normalize all `\u2011` to regular `-`.

5. **Text extraction:** Extract text from each `font1` div using `innerText` or equivalent, collapse all whitespace (including `&nbsp;`) to single spaces, and trim.

---

### Line Classification Rules

After extracting and sorting all lines by `absolute_top`, classify each line as one of these types:

| Type | How to identify |
|---|---|
| **SKIP** | Matches any of: starts with 5+ dashes `-----`, matches `D E S C R I P T I O N`, contains `S.F.MEDICAL AGENCY` as a standalone header, contains `PARTY / ITEM WISE SALES SUMMARY`, starts with `5/38`, starts with `Phone :`, starts with `GSTIN :`, starts with `Report For`, starts with `Company :`, contains `Continued..`, contains `Page No..` |
| **TOTAL ROW** | Contains the word `TOTAL :` — skip these |
| **PARTY NAME** | A non-empty line that does **not** match the item pattern (see below) and does **not** contain a 3-or-more digit number |
| **ITEM ROW** | The last 5 space-separated tokens of the line match: `qty` (number or `-`), `free` (number or `-`), `rate` (decimal number), `amount` (decimal number), `pct` (decimal number). Everything before these 5 tokens is the Item Name. |

---

### Data Extraction Logic

```
current_party = null
records = []

for each line (sorted by absolute_top, ascending):
    if line is SKIP → continue
    if line is TOTAL ROW → continue
    if line is ITEM ROW:
        parse last 5 tokens as: qty, free, rate, amount, pct
        item_name = everything before those 5 tokens
        if free == "-": free = "0"
        append { party: current_party, item_name, qty, free, rate, amount } to records
    else if line is PARTY NAME:
        current_party = line text (trimmed)
```

**Negative values are valid** (e.g., sales returns). Do not discard lines where qty or amount starts with `-`.

---

### Output Excel File Structure

Use the **SheetJS (xlsx.js)** library (load from CDN: `https://cdn.sheetjs.com/xlsx-0.20.3/package/dist/xlsx.full.min.js`) to generate the `.xlsx` file client-side.

The output Excel file must have:

**Sheet name:** `Sales Data`

**Columns (in this order):**

| Column | Header | Notes |
|---|---|---|
| A | Party Name | Text |
| B | Item Name | Text |
| C | Qty | Number (integer) |
| D | Free | Number (integer) |
| E | Rate | Number (2 decimal places) |
| F | Amount | Number (2 decimal places) |

**Formatting requirements:**
- Row 1 = header row with **bold text**, light blue background (`#BDD7EE`), center-aligned, font size 12
- Data rows alternate between white (`#FFFFFF`) and very light grey (`#F2F2F2`) for readability
- Column widths: Party Name = 30 chars, Item Name = 35 chars, Qty = 8, Free = 8, Rate = 12, Amount = 14
- Freeze the top header row (freeze pane at A2)
- Numbers in columns C, D, E, F must be stored as actual numbers (not strings) so Excel can SUM them
- File should download automatically as `SPECIALITY_Sales_Data.xlsx`

---

### UI / UX Requirements

The web app should be a **single HTML file** with embedded CSS and JS. The UI must include:

1. **Title bar:** "Invoice HTML → Excel Converter" in a clean header
2. **Upload zone:** A drag-and-drop area AND a file input button. Accepts only `.html` and `.htm` files. Shows the selected filename once chosen.
3. **Convert button:** Disabled until a file is selected. Labelled "Convert & Download Excel".
4. **Progress/status area:** After clicking Convert, show:
   - "Parsing HTML..." while reading
   - "X records found across Y parties." after parsing
   - "Generating Excel file..." while building xlsx
   - "✅ Done! File downloaded." on success
   - "❌ Error: [message]" in red if anything fails
5. **Preview table:** After parsing, display the first 20 rows in a styled HTML table inside the page so the user can verify data before downloading. Show columns: Party Name, Item Name, Qty, Free, Rate, Amount. If more than 20 rows exist, show a note: "Showing 20 of X rows."
6. **Reset button:** Appears after conversion, clears everything and resets to upload state.

---

### Error Handling

- If no `font1` divs are found → show error: "No data found. Please check this is a valid SPECIALITY report file."
- If file cannot be read → show error: "Could not read file."
- If a parsed record has `null` party name → skip it silently (do not crash).
- Wrap the entire parsing and export logic in try/catch and surface any errors in the status area.

---

### Tech Stack Constraints

- **Pure vanilla JS** — no React, Vue, jQuery, or any other JS framework
- **One single `.html` file** — all CSS and JS inline/embedded
- **Only one external CDN dependency:** SheetJS for Excel generation
- Must work in **Chrome, Firefox, Edge** (modern browsers)
- No server-side code, no Node.js — everything runs in the browser using `FileReader` API

---

### Complete Flow Summary

```
User opens app
  → Drags or selects an .html file
  → Clicks "Convert & Download Excel"
    → FileReader reads file as text (encoding: treat as UTF-8 after browser loads it,
       since the browser will handle windows-1252 declared in the meta tag)
    → DOMParser parses the HTML string into a document object
    → Extract all div.font1 elements from all div.page elements
    → For each page div, record its page_index (0-based order in document)
    → For each font1 div: extract top value from style, compute absolute_top
    → Extract and clean text content
    → Sort all lines by absolute_top
    → Classify and extract records per rules above
    → Display preview table (first 20 rows)
    → Build xlsx workbook with SheetJS with formatting
    → Trigger download of .xlsx file
    → Show success message
```

---

*The HTML input format will always follow this exact structure. Do not add support for other formats. Do not make the parser configurable. Build exactly what is described above.*

---

This prompt is self-contained — hand it to any AI agent (GPT-4o, Gemini, another Claude instance, etc.) and they will have everything they need to produce the full working code in one shot.
